export const colors = [
  { name: "Lexstar", value: "#fffdf6" },
  { name: "Red", value: "#FF0000" },
  { name: "Green", value: "#00FF00" },
  { name: "Blue", value: "#0000FF" },
  { name: "Yellow", value: "#FFFF00" },
  { name: "Purple", value: "#800080" },
  { name: "Gray", value: "#808080" },
  { name: "Orange", value: "#FFA500" },
  { name: "Pink", value: "#FFC0CB" },
  { name: "Brown", value: "#A52A2A" },
  { name: "Cyan", value: "#00FFFF" },
  { name: "Magenta", value: "#FF00FF" },
  { name: "Lime", value: "#00FF00" },
  { name: "Teal", value: "#008080" },
  { name: "Lavender", value: "#E6E6FA" },
  { name: "Olive", value: "#808000" },
  { name: "Maroon", value: "#800000" },
  { name: "Navy", value: "#000080" },
  { name: "Aquamarine", value: "#7FFFD4" },
  { name: "Turquoise", value: "#40E0D0" },
  { name: "Silver", value: "#C0C0C0" },
  { name: "Gold", value: "#FFD700" },
  { name: "Beige", value: "#F5F5DC" },
  { name: "Coral", value: "#FF7F50" },
  { name: "Indigo", value: "#4B0082" },
  { name: "Violet", value: "#EE82EE" },
  { name: "Crimson", value: "#DC143C" },
  { name: "Khaki", value: "#F0E68C" },
  { name: "Mint", value: "#98FF98" },
  { name: "Peach", value: "#FFDAB9" },
  { name: "Chocolate", value: "#D2691E" },
  { name: "Salmon", value: "#FA8072" },
  { name: "Plum", value: "#DDA0DD" },
  { name: "Orchid", value: "#DA70D6" },
  { name: "Tan", value: "#D2B48C" },
  { name: "Slate", value: "#708090" },
  { name: "Sky Blue", value: "#87CEEB" },
  { name: "Periwinkle", value: "#CCCCFF" },
  { name: "Ivory", value: "#FFFFF0" },
  { name: "Honeydew", value: "#F0FFF0" },
  { name: "Lemon", value: "#FFFACD" },
  { name: "Blush", value: "#DE5D83" },
  { name: "Fuchsia", value: "#FF00FF" },
  { name: "Azure", value: "#F0FFFF" },
  { name: "Wheat", value: "#F5DEB3" },
  { name: "Sea Green", value: "#2E8B57" },
  { name: "Forest Green", value: "#228B22" },
  { name: "Steel Blue", value: "#4682B4" },
  { name: "Rosy Brown", value: "#BC8F8F" },
  { name: "Light Pink", value: "#FFB6C1" },
];
